site:
  start_page: portx::index.adoc
  title: ModusBox for Any ESB
  url: https://docs.portx.io

content:
  sources:
  - url: ../modusbox-docs
    branches: [HEAD]
    start_path: as2-connector

  - url: ../modusbox-docs
    branches: [HEAD]
    start_path: ftps-connector

  - url: ../modusbox-docs
    branches: [HEAD]
    start_path: jde

  - url: ../modusbox-docs
    branches: [HEAD]
    start_path: portx

  - url: ../modusbox-docs
    branches: [HEAD]
    start_path: portx-connector

  - url: ../modusbox-docs
    branches: [HEAD]
    start_path: release-notes

asciidoc:
  attributes:
    camel: ''
    experimental: ''
    idprefix: ''
    idseparator: '-'
    linkattrs: ''
    product: 'PortX'

output:
  destinations:
  - provider: fs
    path: build/site
    clean: true
ui:
  bundle:
    url: ./portx-ui/build/ui-bundle.zip
    snapshot: true
  supplemental_files: ./build-resources/supplemental_ui
runtime:
  pull: true
